name: virtual_device
description: Discover, run, stop, create, and destroy iOS simulators and Android emulators
version: 0.0.4
homepage: https://github.com/tshedor/virtual_device

environment:
  sdk: ">=2.7.0 <3.0.0"

executables:
  virtual_device:

dependencies:
  args: ^1.6.0
  meta: ^1.2.4
  uuid: ^2.2.2

dev_dependencies:
  test: ^1.14.3
