name: virtual_device
description: Manage and create iOS simulators and Android emulators
version: 0.0.1+1
homepage: https://github.com/tshedor/virtual_device

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^1.6.0
  meta: ^1.2.4

dev_dependencies:
  test: ^1.14.3
