name: virtual_device
description: Discover, run, stop, create, and destroy iOS simulators and Android emulators
version: 1.0.0
homepage: https://github.com/tshedor/virtual_device

environment:
  sdk: ">=2.12.0 <3.0.0"

executables:
  virtual_device:

dependencies:
  args: ^2.0.0
  meta: ^1.3.0
  uuid: ^3.0.1

dev_dependencies:
  test: ^1.16.7
